name: 'Generate Vector tiles'
description: 'generate mbtiles with tippeacanoe'
inputs:
  input_files:
    description: 'Converting geometries'
    required: true
  output_dir:
    description: '*.MVT output dir'
    required: false
    default: tiles
  source_layer_name:
    description: 'mbtiles source layer name'
    required: false
    default: out

runs:
  using: docker
  image: Dockerfile

  args:
    - ${{ inputs.input_files }}
    - ${{ inputs.output_dir }}
    - ${{ inputs.source_layer_name }}